services:
  postgres:
    image: ${DOCKER_IMAGE}
    restart: on-failure
    container_name: ${DOCKER_CONTAINER}
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_SCHEMA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${HOST_PORT}:5432"
    volumes:
      - ./:/bootcamp/
      - ./data.dump:/docker-entrypoint-initdb.d/data.dump
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres-data:/var/lib/postgresql/data
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: on-failure
    container_name: cloudbeaver
    ports:
      - "${CLOUDBEAVER_PORT}:8978"
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
volumes:
  postgres-data:
  cloudbeaver-data:
